### ISSUE TITLE
Lab 1: Data Modeling > Task 1 > Create Expenses Table and Columns issue

### ISSUE THREAD

**Issue by Srikanthssp** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#117] opened 2024-11-14 14:42 UTC
# Module 2: Identify foundational components of Microsoft Power Platform
#### Step: Create Expense Type Column > step 6

Description of issue : As mentioned in the lab guide, I cannot see the Expense Type from the list of choices available

**In Sync this choice with field, select Expense Type.**

![image](https://github.com/user-attachments/assets/6c1f30ce-ece5-4f70-96b6-5556bece25d6)

Do we need to create a new choice with the same name and provide label?

@CeleneA , can you please check on this issue?

**Comment by a-ainamdar** [comment] 2024-11-14 14:56
Hi Shrikanth
I hope you are well.
I have just tested this and I can see Expense Type from the list. This issue is not reproducible at our end.

Please find attached screenshot below and let me know in case of any issues.
![image](https://github.com/user-attachments/assets/2c73876f-8ecb-4c66-9c71-3c163ec55463)

Thank you
Ashwini

**Comment by Srikanthssp** [comment] 2024-11-14 15:50
It is available by Default? Do we need to create it first?, I have created a Trial environment and performing this task, but I cannot see Expense Type from the list. Do I need to perform this in different environment?

**Comment by a-ainamdar** [comment] 2024-11-14 15:54
Have you selected Dev One Environment?
It is available by Default.

**Comment by Srikanthssp** [comment] 2024-11-14 15:55
I signed up for Powerapps Trial and I did not found any Dev One Environment, So I have created Trial environment and started performing.

**Comment by a-ainamdar** [comment] 2024-11-14 15:57
Any reason you are using Powerapps Trial?

**Comment by Srikanthssp** [comment] 2024-11-14 16:00
Do I need to purchase any license to get that Dev One environment?

**Comment by CeleneA** [comment] 2024-11-14 16:24
@Srikanthssp,
the labs have been developed specifically against the tenant that is used for ILT deliveries. They are not intended to be used with trial environments or outside the context of a course delivery.

Please let me know which training provider you are working with. They should be able to provide you with access to the course tenant.

**Comment by CeleneA** [comment] 2024-11-14 21:48
@Srikanthssp,
I am going to close this issue. If you are still experiencing issues, please contact the training provider you are working with.

**Closed by CeleneA** 2024-11-14 21:48 UTC
